version: "3.8"
services:
  app:
    env_file: .env
    build: .
    command: streamlit run app/main.py --server.port 8501
    volumes:
        - .:/app
    ports:
        - 443:8501
    image: bpho-projectiles:latest
