[tool.poetry]
name = "projectiles-cc"
version = "0.1.0"
description = ""
authors = ["Kenneth Lew", "Timothy Ka"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.34.0"
seaborn = "^0.13.2"
matplotlib = "^3.9.0"
pandas = "^2.2.2"


[tool.poetry.group.dev.dependencies]
watchdog = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
