# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bpho-projectiles

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9a5be997478e462d8828905678c83b9f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_15c6be7b642640e393a2507b0f67d2e5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_9a5be997478e462d8828905678c83b9f }}/bpho-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bpho-projectiles'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_94b22b966ec244a0bbf71354321ac5d0 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_9a5be997478e462d8828905678c83b9f }}/bpho-image:${{ github.sha }}'