[runner]
magicEnabled = true

[server]
runOnSave = true
enableCORS = true
enableXsrfProtection = true

[ui]
hideTopBar = true

[client]
toolbarMode = "minimal"
showErrorDetails = false

[theme]
base = "dark"
font = "sans serif"
